services:
  webapp:
    container_name: ${WEBAPP_HOST}
    image: ghcr.io/murias10/teachingplanner/webapp:latest
    ports:
      - "${WEBAPP_PORT}:80" # Mapeo: puerto del host (WEBAPP_PORT) → puerto 80 en el contenedor
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app_network

  gateway_service:
    container_name: ${GATEWAY_SERVICE_HOST}
    build:
      context: ./gateway_service
      dockerfile: Dockerfile
    ports:
      - "${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}" # Mapeo: mismo puerto en host y contenedor (GATEWAY_SERVICE_PORT)
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - planner_service
    networks:
      - app_network

  planner_service:
    container_name: planner_service # Nombre descriptivo del contenedor del servicio de la aplicación
    image: ghcr.io/murias10/teachingplanner/planner_service:latest
    expose:
      - "${PLANNER_SERVICE_PORT}"   # Solo comunicación interna: servicio escucha en PLANNER_SERVICE_PORT
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      planner_database:
        condition: service_healthy # Espera hasta que MariaDB esté listo antes de iniciar
    networks:
      - app_network # Conecta el servicio de la aplicación web y MariaD

  planner_database:
    container_name: ${PLANNER_DATABASE_HOST}
    image: ghcr.io/murias10/teachingplanner/planner_database:latest
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ] # Verifica si el servicio está activo
      interval: 10s # Revisión cada 10 segundos
      retries: 5 # Número de intentos antes de considerar que el servicio está fallando
    volumes:
      - planner_database_volume:/var/lib/mysql # Persistencia de datos de la base de datos
    ports:
      - "${PLANNER_DATABASE_PORT}:${PLANNER_DATABASE_PORT}"
    expose:
      - "${PLANNER_DATABASE_PORT}"
    networks:
      - app_network # Conecta MariaDB y la aplicación web

volumes:
  planner_database_volume:

networks:
  app_network:
    driver: bridge # Red dedicada para mejorar la comunicación entre servicios
