services:
  webapp:
    container_name: webapp_service # Nombre descriptivo del contenedor de la aplicación
    image: ghcr.io/murias10/teachingplanner/webapp:latest
    ports:
      - "80:80" # Expone el puerto 80 en el host para acceder a la aplicación web
    # depends_on:
    #   mariadb:
    #     condition: service_healthy # Espera hasta que MariaDB esté listo antes de iniciar
    restart: unless-stopped # Reinicia el servicio solo si falla, pero no si se detiene manualmente
    env_file:
      - .env
    networks:
      - app_network # Red interna para permitir la comunicación con MariaDB

  planner_service:
    container_name: planner_service # Nombre descriptivo del contenedor del servicio de la aplicación
    image: ghcr.io/murias10/teachingplanner/planner_service:latest
    restart: always # Asegura que el servicio siempre se reinicie si falla
    environment:
      DATABASE_URL: mysql://myuser:mypassword@planner_database/mydatabase # URL de conexión a la base de datos MariaDB
    depends_on:
      planner_database:
        condition: service_healthy # Espera hasta que MariaDB esté listo antes de iniciar
    networks:
      - app_network # Conecta el servicio de la aplicación web y MariaDB

  planner_database:
    container_name: planner_database # Nombre descriptivo del contenedor de MariaDB
    image: ghcr.io/murias10/teachingplanner/planner_database:latest
    restart: always # Asegura que el servicio siempre se reinicie si falla
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword # Contraseña del usuario root de MariaDB
      MARIADB_DATABASE: mydatabase # Base de datos que se creará al iniciar
      MARIADB_USER: myuser # Usuario de la base de datos
      MARIADB_PASSWORD: mypassword # Contraseña del usuario de la base de datos
    volumes:
      - planner_data:/var/lib/mysql # Persistencia de datos de la base de datos
    ports:
      - "3306:3306" # Permite acceso desde el host en desarrollo (quitar en producción)
    expose:
      - "3306" # Expone el puerto solo dentro de la red de Docker para comunicación interna
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ] # Verifica si el servicio está activo
      interval: 10s # Revisión cada 10 segundos
      retries: 5 # Número de intentos antes de considerar que el servicio está fallando
    networks:
      - app_network # Conecta MariaDB y la aplicación web

volumes:
  planner_data:
    # Volumen para la persistencia de datos de MariaDB

networks:
  app_network:
    driver: bridge # Red dedicada para mejorar la comunicación entre servicios
