CREATE TABLE DEGREE (
    ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(100) NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);

CREATE TABLE COURSE (
    ID VARCHAR(36) NOT NULL,
    ID_DEGREE VARCHAR(36) NOT NULL,
    START_YEAR SMALLINT NOT NULL,
    END_YEAR SMALLINT NOT NULL,
    STATE VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_DEGREE) REFERENCES DEGREE(ID),
    UNIQUE KEY UQ_COURSE_UNIQUE (ID_DEGREE, START_YEAR, END_YEAR)
);

CREATE TABLE CALENDAR (
    ID VARCHAR(36) NOT NULL,
    ID_COURSE VARCHAR(36) NOT NULL,
    SEMESTER SMALLINT NOT NULL CHECK (SEMESTER IN (1, 2)),
    START TIMESTAMP NOT NULL,
    END TIMESTAMP NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_COURSE) REFERENCES COURSE(ID),
    UNIQUE KEY UQ_CALENDAR_UNIQUE (ID_COURSE, SEMESTER)
);

CREATE TABLE DAY (
    ID VARCHAR(36) NOT NULL,
    ID_CALENDAR VARCHAR(36) NOT NULL,
    COMMENT BIGINT NOT NULL,
    DATE TIMESTAMP NOT NULL,
    LECTIVE BOOLEAN NOT NULL,
    CHARACTERS VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_CALENDAR) REFERENCES CALENDAR(ID),
    UNIQUE KEY UQ_DAY_UNIQUE (ID_CALENDAR, DATE)
);

CREATE TABLE EVENT (
    ID VARCHAR(36) NOT NULL,
    ID_DAY VARCHAR(36) NOT NULL,
    START_TIME TIME NOT NULL,
    END_TIME TIME NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    CANCELLED BOOLEAN NOT NULL,
    COMMENT VARCHAR(255) NOT NULL,
    CHARACTER VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_DAY) REFERENCES DAY(ID)
);

CREATE TABLE EVENT_GROUP (
    ID_EVENT VARCHAR(36) NOT NULL,
    ID_GROUP VARCHAR(36) NOT NULL,
    PRIMARY KEY (ID_EVENT, ID_GROUP),
    FOREIGN KEY (ID_EVENT) REFERENCES EVENT(ID),
    FOREIGN KEY (ID_GROUP) REFERENCES GROUP(ID)
);

CREATE TABLE EVENT_CALASSROOM (
    ID_EVENT VARCHAR(36) NOT NULL,
    ID_CLASSROOM VARCHAR(36) NOT NULL,
    PRIMARY KEY (ID_EVENT, ID_CLASSROOM),
    FOREIGN KEY (ID_EVENT) REFERENCES EVENT(ID),
    FOREIGN KEY (ID_CLASSROOM) REFERENCES CLASSROOM(ID)
);

CREATE TABLE CLASSROOM (
    ID VARCHAR(36) NOT NULL,
    CODE BIGINT NOT NULL UNIQUE,
    GIS_URL BIGINT NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);

CREATE TABLE GROUP (
    ID VARCHAR(36) NOT NULL,
    ID_SUBJECT VARCHAR(36) NOT NULL,
    NUMBER BIGINT NOT NULL UNIQUE,
    TYPE VARCHAR(50) NOT NULL,
    LANGUAGE VARCHAR(2) NOT NULL CHECK (LANGUAGE IN ('EN', 'ES')),
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_SUBJECT) REFERENCES SUBJECTS(ID)
);

CREATE TABLE SUBJECTS (
    ID VARCHAR(36) NOT NULL,
    ACRONYM VARCHAR(20) NOT NULL UNIQUE,
    SEMESTER BIGINT NOT NULL CHECK (SEMESTER IN (1, 2)),
    COURSE VARCHAR(36) NOT NULL,
    YEAR BIGINT NOT NULL,
    NAME VARCHAR(100) NOT NULL UNIQUE,
    SIES_CODE VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID)
);
